name: 'Action docker compose deploy'
description: 'Deploy service to remote serve'
author: 'Muhammad Azizol Aminuddin'
inputs:
  username:
    required: true
    description: 'username for ssh'
  host:
    required: true
    description: 'host for ssh'
  privateKey:
    required: true
    description: 'private key for ssh'
  sha8:
    required: true
    description: 'Sha8 for this commit'
runs:
  using: 'node12'
  main: 'dist2/index.js'
